### ISSUE TITLE
Missing the calculation of "ave_glue" in  model.py "nat_cost" function.

### ISSUE THREAD

**Issue by llamazing** [ictnlp/RSI-NAT#1]
https://github.com/ictnlp/RSI-NAT/blob/d0f3638c7bad0739f5c7647145ed88d134bd8254/model.py#L1158

Thanks for your work.
 I found that there is no "ave_glue" calculation before it used in nat_cost() function. Can you help solve this problem?

**Comment by shaochenze** [comment]
Sorry for the late reply. This is the baseline reward technique which found to be unhelpful here. You can replace this line by https://github.com/ictnlp/RSI-NAT/blob/2f6003773befcc60393bddd504582cdf9928b943/model.py#L1158 or download our latest code.
