### ISSUE TITLE
Why there is an error?

### ISSUE THREAD

**Issue by shushengyuan** [ictnlp/RSI-NAT#2]
when i clone your source codes in pycharm,i find out that there is an error at line 1214 in the 'model' moudule.

`        return targets[input_mask], out[out_mask].view(-1, out.size(-1)), the_mask`

The error shows : the  unresolved reference 'the_mask'.
And i actually cannot find the 'the_mask' in the **mask**  function.

Thanks.

**Comment by shaochenze** [comment]
Hi, you can delete the **mask** function since it is never called. The code is cloned from [dl4mt-nonauto](https://github.com/nyu-dl/dl4mt-nonauto "dl4mt-nonauto") and we didn't notice the problem. Thanks for your issue.

**Comment by shushengyuan** [comment]
ok, thanks for your feedback.
