### ISSUE TITLE
Is this normal ?

### ISSUE THREAD

**Issue by shushengyuan** [ictnlp/RSI-NAT#3]
when we try to train a new model by your source code,we find the logs are like followings:

> 2019-09-07 19:18:53 INFO: - iter 1 | BLEU = 0.00, 0.0/0.0/0.0/0.0 (BP=1.000, ratio=1.087)
2019-09-07 19:18:53 INFO: - iter 2 | BLEU = 0.00, 0.0/0.0/0.0/0.0 (BP=1.000, ratio=1.087)
2019-09-07 19:18:53 INFO: - best model : BLEU=[0.0, 0.0], i=999

Is this situation normal ? 
Thanks.

**Comment by shaochenze** [comment]
Which dataset are you using? It is normal for WMT datasets, and BLEU will be nonzero when i=1999.

**Comment by shushengyuan** [comment]
sorry for the late response.

i am using the **iwlst** datasets,and i am trying to train the model these days, but i still can`t observe a good result even the loss is 1.0.

We did two experiments :  
One ran with the source code,the results are following:

> 2019-09-07 19:18:53 INFO: - iter 1 | BLEU = 0.00, 0.0/0.0/0.0/0.0 (BP=1.000, ratio=1.087)
2019-09-07 19:18:53 INFO: - iter 2 | BLEU = 0.00, 0.0/0.0/0.0/0.0 (BP=1.000, ratio=1.087)
2019-09-07 19:18:53 INFO: - best model : BLEU=[0.0, 0.0], i=999

The other ran by my own framework with the NAT model,the results are following:

>  [Train][63/1105/455]   ACC-0.000   LOSS-0.980   TIME-0.25
[Train][62/1105/455]   ACC-0.000   LOSS-1.660   TIME-0.25
[Train][iter/sum_iters/epoches]

Both were trained by one 1080Ti for one day.
Then we checked the source codes, but it seemed ok to the NAT model.
So, do you know the reason and would you like telling us?

(by the way ,what the means of **i**? The source code is a little hard to read : )

Honestly, thanks.

**Comment by shushengyuan** [comment]
Nice! It seems that i have found out the question.
Thank you a lot.
