### ISSUE TITLE
where can I find some code about FS-Decoder?

### ISSUE THREAD

**Issue by JackHorse** [ictnlp/RSI-NAT#4]
Hi

I want to train your FS-Decoder model, but i can't find code about that.

Is it not release ？

**Comment by shaochenze** [comment]
Yes, the code for FS-Decoder is not released yet.

**Comment by JackHorse** [comment]
ok, thanks

**Comment by aitaita-research** [comment]
Does the FS-Decoder model available now? We are interested in your work.
